name: CI/CD workflow
on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: 检查仓库代码
        uses: actions/checkout@v4
      - run: echo "💡 仓库代码检查完毕"

      - name: 设置python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: echo "🐍 设置python环境成功!"

      - name: 安装依赖
        run: |
          pip install -r requirements.txt
          pip install ruff
          echo "📦 安装依赖成功!"

      - name: 执行代码检查
        run: |
          ruff check .
          echo "📦 执行代码检查成功!"

      - name: 构建Docker镜像
        run: |
          docker build -t inkai .
          echo "📦 构建Docker镜像成功!"

      - name: 登录并推送GitHub包仓库
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor}} --password-stdin
          REPO = (echo "${{ github.repository }}"" | tr '[:upper:]' '[:lower:]')
          docker tag inkai ghcr.io/$REPO:latest
          docker push ghcr.io/$REPO:latest
          echo "📦 登录并推送GitHub包仓库成功!"
